// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcwybfzphlrsnxxfhvpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjd3liZnpwaGxyc254eGZodnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTk5MDksImV4cCI6MjA2NDY3NTkwOX0.PY0tsRXWSDWQWi0J8cVnwWKOjrGosnb9TANOjWeb96k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);